services:
  wb_l0:
    restart: unless-stopped
    container_name: wb_l0
    build:
      context: .
      dockerfile: Dockerfile
    command: go run /app/cmd/main.go
    ports:
      - "8080:8080"


  postgres_db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=alex_l0
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=0000
    restart: unless-stopped
    ports:
      - "5432:5432"
  nats:
    image: nats-streaming:latest
    expose:
      - 4222
    ports:
      - "4222:4222"
      - "8222:8222"